### ISSUE TITLE
Why? (Nahuya?)

### ISSUE THREAD

**Issue by visortelle** [devlato/goatse-npm#1]

**Comment by devlato** [comment]
@visortelle Why not? Shuyali net?

**Comment by visortelle** [comment]
@devlato, what is use-case? Just maybe I am not a target audience of this product.

**Comment by devlato** [comment]
@visortelle As you said, you're not the target audience. I don't have to explain anything to you because I'm not trying to force you using the project. It wasn't me who contacted you, it was you who raised an issue here. If you don't see the purpose of using the package, just feel free to close the tab and never visit this repo.

**Comment by visortelle** [comment]
OK dude. Don't pay attention.
